### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by svexican** [UN-DESA-Modelling/UN-DESA-Modelling.github.io#29]
The following links need to be updated:

**electrification paths**
- [ ] Explore button => http://un-desa-modelling.github.io/electrification-paths-presentation/
- [ ] Image => http://un-desa-modelling.github.io/electrification-paths-presentation/
- [ ] Supplementary materials: https://github.com/UN-DESA-Modelling/electrification-paths-supplementary/

**tax fuel and development**
- [ ] Explore button => http://un-desa-modelling.github.io/tax-fuel-development-presentation/
- [ ] Supplementary materials: https://github.com/UN-DESA-Modelling/tax-fuel-development-supplementary/
- [ ] Image => http://un-desa-modelling.github.io/tax-fuel-development-presentation/

**clews-mauritius**
- [ ] Explore button => http://un-desa-modelling.github.io/clews-mauritius-presentation/
- [ ] Supplementary materials: https://github.com/UN-DESA-Modelling/clews-mauritius-supplementary/
- [ ] Image => http://un-desa-modelling.github.io/clews-mauritius-presentation/

**Comment by svexican** [comment]
Is this finished? **The website links are broken**. This is **not**  irrelevant.

**Comment by unite-analytics** [comment]
Thanks guys it seems all links are ok now. Does anyone know how long they were broken for? @RK900 @svexican

**Comment by svexican** [comment]
Some were broken for a long time. Others still redirect to the UN's servers. Others had to be updated because I reorganised all of the repositories.

Who are you? "unite-analytics" is a bit abstract.

**Comment by RK900** [comment]
@unite-analytics I'm not sure how long they were broken for. I think most redirected to UN's servers.

**Comment by unite-analytics** [comment]
@svexican I am a robot = ) Falso, soy Jorge. @RK900 and @LordDarkula have been maintaining the parent modeling site feel free to interact with them of anything is wrong. By the way @RK900 i recall you guys had done many changes on the dev site, did you ever port those to the prod site? Have a nice week.

**Comment by RK900** [comment]
@unite-analytics I was just about to ask you that. I think that it is time that we update the main site with the dev site code. Shall I go ahead and update the main site?

**Comment by unite-analytics** [comment]
Hello. Thanks @RK900 go ahead when you feel you have a decent version and incorporates all the recent changes in prod. Thanks again!
